PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dbo: <http://dbpedia.org/ontology/>
SELECT ?label, ?pic, ?abstract WHERE {
{ 
    ?s rdfs:label "Bob Marly"@en .
    {
        ?s rdfs:label    ?label    ;
           dbo:thumbnail ?pic      ;
           dbo:abstract  ?abstract
    }
    UNION
    {
        ?s dbo:wikiPageDisambiguates ?actualResource .
        ?actualResource rdfs:label    ?label     ; 
                        dbo:thumbnail ?pic       ;
                        dbo:abstract  ?abstract
        FILTER(lang(?label) = "en")
    }
    UNION
    {
        ?s dbo:wikiPageRedirects ?actualResource .
        ?actualResource rdfs:label    ?label     ; 
                        dbo:thumbnail ?pic       ;
                        dbo:abstract  ?abstract
        FILTER(lang(?label) = "en")
    }
}
FILTER (lang(?abstract) = "en")
}